spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        appcode: 8b25a47a382b4e688cbe8f03c5143640
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: xmall97
      access-key: LTAI5tFgs3DVq1DcPAUe3CAx
      secret-key: ePyxIt9D4rPeYXTIDSKiqqciIfuHiV
  application:
    name: xmall-third-party
  main:
    allow-circular-references: true
server:
  port: 30000

