spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: xmall-product
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tFgs3DVq1DcPAUe3CAx
      secret-key: ePyxIt9D4rPeYXTIDSKiqqciIfuHiV
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 6000

logging:
  level:
    com.example: debug
