server:
  port: 22000
spring:
  application:
    name: xmall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8838
    alibaba:
      seata:
        tx-service-group: seata-server-sh
  redis:
    host: 192.168.56.10
  main:
    allow-circular-references: true
