server:
  port: 22000
spring:
  application:
    name: xmall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.56.10
  main:
    allow-circular-references: true
seata:
  tx-service-group: my_test_tx_group
  application-id: seata-server