spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8838
  application:
    name: xmall-auth-server
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.10
    port: 6379
  session:
    store-type: redis
  main:
    allow-circular-references: true
server:
  port: 20000
  servlet:
    session:
      timeout: 30m

